#! /bin/sh

STYLE="m4v"
AUDIO="-N jpn -E ffac3  -6 5point1 -R Auto -B 256 -D 2.0"
GRAPH="-w 1920 --crop 140:140:0:0 -e x264 -q 23 -r 60"
HANDBRAKE="/usr/bin/HandBrakeCLI -f mp4 -4  --verbose=1 --pfr --detelecine --decomb --encopts level=4.2:ref=6:weightp=1:subq=2:rc-lookahead=10:trellis=2:8x8dct=0:bframes=5:b-adapt=2"
OUT="/c/media/iPad/Videos"
EXT="$*"

export STYLE
export AUDIO
export GRAPH
export HANDBRAKE
export OUT
export EXT
/utage/handbrake-worker

