#! /bin/sh

if [ "" != "$1" ]
then
  mongorestore -u 7korobi -p kotatsu3 --host mongo.family.jp -d giji --objcheck --journal --collection $1 /data/mongo/giji/$1.bson 
else
  mongorestore -u 7korobi -p kotatsu3 --host mongo.family.jp -d giji --objcheck --journal 
fi

