#! /bin/sh
# cd /c/media/Album

BACKUPDIR=/c/backup
BACKUPLOG=/c/backup/backup.log

test -e "$BACKUPDIR" || mkdir -p $BACKUPDIR
touch $BACKUPLOG
chmod 777 $BACKUPLOG

echo "`date` backup start" >> $BACKUPLOG
TO=243
ssh -p ${TO}0 7korobi@192.168.0.$TO /utage/mongo/backup_giji  >>  $BACKUPLOG
rsync -av -e "ssh -p ${TO}0" --link-dest -r 7korobi@192.168.0.$TO:/data/www/giji_mongo/ $BACKUPDIR/www/giji_mongo/

TO=245
ssh -p ${TO}0 7korobi@192.168.0.$TO /utage/sow/backup_giji    >>  $BACKUPLOG
rsync -av -e "ssh -p ${TO}0" --link-dest -r 7korobi@192.168.0.$TO:/data/www/ $BACKUPDIR/www/
echo "`date` backup end" >> $BACKUPLOG
