#! /bin/sh

for TO in 
do
  mkdir -p etc/$TO/.git var/$TO/.git home/$TO/.git
  ssh -p ${TO}0 root@192.168.0.$TO  "
    cd /etc/   && git init && git add  /etc/fstab /etc/hosts /etc/ssh/sshd_config /etc/sysconfig/network-scripts/ifcfg-eth0 /etc/yum.repos.d
    cd /var/   && git init && git add  /var/spool/
    cd /home/  && git init
    yum update
  "

  if [ "252" = ${TO} ]
  then
    ssh -p ${TO}0 root@192.168.0.$TO  "
      cd /tmp/
      yum install lftp mongo-10gen
    "
  fi
done

