#! /bin/sh

cd /c/media/Album
git add .
git commit -a -m "collection"

cd /utage/
git add .
git commit -a -m "backup"


TO=243
ssh -p ${TO}0 7korobi@192.168.0.$TO /utage/mongo/backup_giji

SRC=/data/mongo/$TARGET
OLD=`ls -dtr /c/backup/data/${TARGET}* | tail -1`
date "+${TARGET}-%Y-%m-%d" | xargs mkdir
NEW=`ls -dtr /c/backup/data/${TARGET}* | tail -1`
rsync -av -e "ssh -p ${TO}0" --link-dest $OLD/ 192.168.0.$TO:$SRC/ $NEW/


for TO in 241 243 251 252 253 254
do
  for DIR in etc var home
  do
    ssh -p ${TO}0 root@192.168.0.$TO "cd /$DIR/  && git commit -a -m backup"
    rsync -r -e "ssh -p ${TO}0" root@192.168.0.$TO:/$DIR/.git/ /c/backup/$DIR/$TO/.git/
  done
done


TO=252
for DIR in giji_rails giji_log giji_socketstream
do
    mkdir -p /c/backup/www/$DIR/
    rsync -r -e "ssh -p ${TO}0" 7korobi@192.168.0.$TO:/www/$DIR/ /c/backup/www/$DIR/
done

