#! /bin/sh

PUBR=`cat /root/.ssh/id_rsa.pub`
PUB7=`cat /c/home/7korobi/.ssh/id_rsa.pub`
PUBD=`cat /c/home/7korobi/.ssh/master.pub`

KEY=/root/.ssh/authorized_keys
echo "chmod 700 /root/.ssh" > /tmp/auth-root
echo "/bin/grep \"$PUB7\" \"$KEY\" || /bin/echo \"$PUB7\" >> \"$KEY\";" >> /tmp/auth-root
echo "/bin/grep \"$PUBR\" \"$KEY\" || /bin/echo \"$PUBR\" >> \"$KEY\";" >> /tmp/auth-root

KEY=/home/7korobi/.ssh/authorized_keys
echo "chmod 700 /home/7korobi/.ssh" > /tmp/auth-7korobi
echo "/bin/grep \"$PUB7\" \"$KEY\" || /bin/echo \"$PUB7\" >> \"$KEY\";" >> /tmp/auth-7korobi
echo "/bin/grep \"$PUBR\" \"$KEY\" || /bin/echo \"$PUBR\" >> \"$KEY\";" >> /tmp/auth-7korobi

for TO in 251 252 253 254
do
    ssh -p ${TO}0    root@192.168.0.$TO  <  /tmp/auth-root
    ssh -p ${TO}0 7korobi@192.168.0.$TO  <  /tmp/auth-7korobi
done


